version: '3.4'
services:
  mysql:
    image: mysql:5.6
    # ports: 
    #   - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - TZ=Asiz/Shanghai
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:rw
      - ./data:/var/lib/mysql

    network_mode: host
