name: import data
on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master
      - "v[0-9]+.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    env:
      LANG: en_US.utf8

    steps:
      - uses: actions/checkout@v2

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.5.4

      - uses: actions/setup-go@v1
        with:
          go-version: 1.16.4

      - name: Cache Hadoop
        uses: actions/cache@v2
        with:
          path: target/data/hadoop-3.2.1.tar.gz
          key: ${{ runner.os }}-hadoop-${{ hashFiles('scripts/generate-data.sh') }}

      - name: Install nebula-graph
        run: |
          mkdir tmp
          pushd tmp
          git clone https://github.com/vesoft-inc/nebula-docker-compose.git
          pushd nebula-docker-compose/
          cp ../../e2e/nebula/docker-compose.yaml .
          docker-compose up -d
          sleep 5
          popd
          popd

      - name: setup go tools
        env:
          CGO_ENABLED: 0
        run: |
          export GOPATH=$HOME/go
          export GOBIN=$(go env GOPATH)/bin
          export PATH=$PATH:$GOBIN
          /bin/bash scripts/setup.sh

      - name: generate the data
        run: |
          python3 run.py data -s 0.1

      - name: import the data
        run: |
          python3 run.py nebula importer

      - name: run stress testing
        run: |
          python3 run.py stress run -d 3
